### ISSUE TITLE
Clang error

### ISSUE THREAD

**Issue by rrajesh011** [BenzoRom/dragontc-7.0#1]
https://www.hastebin.com/uvurazutaj.sql

Device: Moto G5+

Any idea how to fix this

**Comment by mydongistiny** [comment]
Maybe try using a ccache you didn't compile yourself?

**Comment by rrajesh011** [comment]
im using ccache
`USE_CCACHE=1`

**Comment by mydongistiny** [comment]
Do you have git-lfs installed? You need it to download the toolchain from github.

**Comment by rrajesh011** [comment]
`git-lfs
git-lfs/2.4.2 (GitHub; linux amd64; go 1.8.3)
Sorry, no usage text found for "git-lfs"
`
installed still getting same error

**Comment by mydongistiny** [comment]
you would need to grab the toolchain again after installing git-lfs. It grabs the missing big files from github. Just grab it from here: https://bitbucket.org/xanaxdroid/dragontc-7.0

**Comment by rrajesh011** [comment]
`error: art/test/Android.bp:370:1: "libtistressd" depends on undefined module "slicer"`
`error: art/test/Android.bp:364:1: "libtistress" depends on undefined module "slicer"`

what is the solution for this. i simply nuked it

**Comment by rrajesh011** [comment]
exactly i did this :)

but still im confused about toolchain, which toolchain are u talking about, if its about gcc then it is in source

**Comment by rrajesh011** [comment]
https://del.dog/uwesunebag.nginx

somehow i have passed that error but stucked here

**Comment by mydongistiny** [comment]
You are using old source.  external/dng_sdk has polly disabled, but your source is passing polly to it.

**Comment by mydongistiny** [comment]
you need to resync

**Comment by rrajesh011** [comment]
resynced thousand times

**Comment by mydongistiny** [comment]
Well I'm not using git lfs anymore on that repo so....

**Comment by rrajesh011** [comment]
Thanks for ur help Jason,

**Comment by rrajesh011** [comment]
https://del.dog/fuwogeqeso.rb
Getting this, and i have no idea how to solve this.

**Comment by mydongistiny** [comment]
You need to pull the commits from here since I don't have the repo in my manifest

https://github.com/BenzoRom/external_llvm/commits/eightone

**Comment by rrajesh011** [comment]
oh i see, external/llvm is tracking from aosp.
NVM i used this benzo external/llvm.
Thanks again.
